import { Navbar } from "@/components/WorkScoutLayout/NavBar";
import type { Metadata } from "next";
import MobileSideBar from "@/components/WorkScoutLayout/MobileSideBar";
import SideBar from "@/components/WorkScoutLayout/SideBar";
import Chat from "@/components/Chat/Chat";




export const metadata: Metadata = {
  title: "Workscout-onboarding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <main className="h-full relative p-0 w-full">
      <Navbar />
      <MobileSideBar />




      <section className="bg-[#FFFF0] flex justify-start relative">
        <SideBar />
        {children}

      </section>

      <div className="fixed bottom-4 right-4 z-50 flex flex-col items-end ">
        <Chat />
      </div>
    </main>



  );
}
