import type { Metadata } from "next";
import {  Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/HomeLayout/Navbar";
import { Footer } from "@/components/HomeLayout/footer";
import KindeProvider from "./KindeProvider";


const inter = Inter({
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <KindeProvider>
      <html lang="en">
        <body
          className={`${inter.className} h-screen antialiased  bg-snowwhite`}
        >
          <div className="w-full fixed top-0">
            <Navbar />
          </div>

          <main className="h-full">
            {children}
            <Footer />
          </main>



        </body>
      </html>
    </KindeProvider >
  );
}
